/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphics;

/**
 *
 * @author SICHANGI
 */
public class Mainscreen extends javax.swing.JFrame {

    /**
     * Creates new form Mainscreen
     */
    public Mainscreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        issuancePanel = new javax.swing.JPanel();
        vidIssuanceTabbedPane = new javax.swing.JTabbedPane();
        borrowPanel = new javax.swing.JPanel();
        returnPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        vidRecordsPanel = new javax.swing.JPanel();
        vidRecordsTabbedPane = new javax.swing.JTabbedPane();
        owenedVidsPanel = new javax.swing.JPanel();
        addVidPanel = new javax.swing.JPanel();
        deleteVidPanel = new javax.swing.JPanel();
        lentVidsPanel = new javax.swing.JPanel();
        revenuePanel = new javax.swing.JPanel();
        revenueTabbedPane = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        membershipPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        myProfilePanel = new javax.swing.JPanel();
        membersPanel = new javax.swing.JPanel();
        exMembersPanel = new javax.swing.JPanel();
        newMembersPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Upepeo Video Lending system");
        setLocation(new java.awt.Point(60, 50));
        setMaximumSize(new java.awt.Dimension(1780, 800));
        setMinimumSize(new java.awt.Dimension(1700, 800));
        setSize(new java.awt.Dimension(1780, 830));

        issuancePanel.setBackground(new java.awt.Color(143, 188, 143));

        borrowPanel.setBackground(new java.awt.Color(119, 136, 153));

        javax.swing.GroupLayout borrowPanelLayout = new javax.swing.GroupLayout(borrowPanel);
        borrowPanel.setLayout(borrowPanelLayout);
        borrowPanelLayout.setHorizontalGroup(
            borrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1770, Short.MAX_VALUE)
        );
        borrowPanelLayout.setVerticalGroup(
            borrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        vidIssuanceTabbedPane.addTab("Video borrowing", borrowPanel);

        returnPanel.setBackground(new java.awt.Color(119, 136, 153));

        javax.swing.GroupLayout returnPanelLayout = new javax.swing.GroupLayout(returnPanel);
        returnPanel.setLayout(returnPanelLayout);
        returnPanelLayout.setHorizontalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1770, Short.MAX_VALUE)
        );
        returnPanelLayout.setVerticalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        vidIssuanceTabbedPane.addTab("Video returns", returnPanel);

        jPanel1.setBackground(new java.awt.Color(119, 136, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1770, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        vidIssuanceTabbedPane.addTab("wdcd", jPanel1);

        javax.swing.GroupLayout issuancePanelLayout = new javax.swing.GroupLayout(issuancePanel);
        issuancePanel.setLayout(issuancePanelLayout);
        issuancePanelLayout.setHorizontalGroup(
            issuancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vidIssuanceTabbedPane)
        );
        issuancePanelLayout.setVerticalGroup(
            issuancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vidIssuanceTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        mainTabbedPane.addTab("Video issuance", issuancePanel);

        vidRecordsPanel.setBackground(new java.awt.Color(143, 188, 143));

        vidRecordsTabbedPane.setBackground(new java.awt.Color(143, 188, 143));

        owenedVidsPanel.setBackground(new java.awt.Color(245, 245, 220));

        javax.swing.GroupLayout owenedVidsPanelLayout = new javax.swing.GroupLayout(owenedVidsPanel);
        owenedVidsPanel.setLayout(owenedVidsPanelLayout);
        owenedVidsPanelLayout.setHorizontalGroup(
            owenedVidsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1770, Short.MAX_VALUE)
        );
        owenedVidsPanelLayout.setVerticalGroup(
            owenedVidsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        vidRecordsTabbedPane.addTab("Videos in house", owenedVidsPanel);

        addVidPanel.setBackground(new java.awt.Color(245, 245, 220));

        javax.swing.GroupLayout addVidPanelLayout = new javax.swing.GroupLayout(addVidPanel);
        addVidPanel.setLayout(addVidPanelLayout);
        addVidPanelLayout.setHorizontalGroup(
            addVidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1770, Short.MAX_VALUE)
        );
        addVidPanelLayout.setVerticalGroup(
            addVidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        vidRecordsTabbedPane.addTab("Add video", addVidPanel);

        deleteVidPanel.setBackground(new java.awt.Color(245, 245, 220));

        javax.swing.GroupLayout deleteVidPanelLayout = new javax.swing.GroupLayout(deleteVidPanel);
        deleteVidPanel.setLayout(deleteVidPanelLayout);
        deleteVidPanelLayout.setHorizontalGroup(
            deleteVidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1770, Short.MAX_VALUE)
        );
        deleteVidPanelLayout.setVerticalGroup(
            deleteVidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        vidRecordsTabbedPane.addTab("Delete video", deleteVidPanel);

        lentVidsPanel.setBackground(new java.awt.Color(245, 245, 220));

        javax.swing.GroupLayout lentVidsPanelLayout = new javax.swing.GroupLayout(lentVidsPanel);
        lentVidsPanel.setLayout(lentVidsPanelLayout);
        lentVidsPanelLayout.setHorizontalGroup(
            lentVidsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1770, Short.MAX_VALUE)
        );
        lentVidsPanelLayout.setVerticalGroup(
            lentVidsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        vidRecordsTabbedPane.addTab("Videos lent", lentVidsPanel);

        javax.swing.GroupLayout vidRecordsPanelLayout = new javax.swing.GroupLayout(vidRecordsPanel);
        vidRecordsPanel.setLayout(vidRecordsPanelLayout);
        vidRecordsPanelLayout.setHorizontalGroup(
            vidRecordsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vidRecordsTabbedPane)
        );
        vidRecordsPanelLayout.setVerticalGroup(
            vidRecordsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vidRecordsTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        mainTabbedPane.addTab("Video records", vidRecordsPanel);

        revenuePanel.setBackground(new java.awt.Color(143, 188, 143));

        jPanel6.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1770, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        revenueTabbedPane.addTab("tab1", jPanel6);

        jPanel7.setBackground(new java.awt.Color(102, 204, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1770, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        revenueTabbedPane.addTab("tab2", jPanel7);

        jPanel8.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1770, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        revenueTabbedPane.addTab("tab3", jPanel8);

        javax.swing.GroupLayout revenuePanelLayout = new javax.swing.GroupLayout(revenuePanel);
        revenuePanel.setLayout(revenuePanelLayout);
        revenuePanelLayout.setHorizontalGroup(
            revenuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(revenueTabbedPane)
        );
        revenuePanelLayout.setVerticalGroup(
            revenuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(revenueTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        mainTabbedPane.addTab("Revenue", revenuePanel);
        revenuePanel.getAccessibleContext().setAccessibleDescription("on members");

        membershipPanel.setBackground(new java.awt.Color(143, 188, 143));

        jTabbedPane1.setBackground(new java.awt.Color(176, 224, 230));

        myProfilePanel.setBackground(new java.awt.Color(176, 224, 230));

        javax.swing.GroupLayout myProfilePanelLayout = new javax.swing.GroupLayout(myProfilePanel);
        myProfilePanel.setLayout(myProfilePanelLayout);
        myProfilePanelLayout.setHorizontalGroup(
            myProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1770, Short.MAX_VALUE)
        );
        myProfilePanelLayout.setVerticalGroup(
            myProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("My Profile", myProfilePanel);

        membersPanel.setBackground(new java.awt.Color(176, 224, 230));

        javax.swing.GroupLayout membersPanelLayout = new javax.swing.GroupLayout(membersPanel);
        membersPanel.setLayout(membersPanelLayout);
        membersPanelLayout.setHorizontalGroup(
            membersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1770, Short.MAX_VALUE)
        );
        membersPanelLayout.setVerticalGroup(
            membersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Members", membersPanel);

        exMembersPanel.setBackground(new java.awt.Color(176, 224, 230));

        javax.swing.GroupLayout exMembersPanelLayout = new javax.swing.GroupLayout(exMembersPanel);
        exMembersPanel.setLayout(exMembersPanelLayout);
        exMembersPanelLayout.setHorizontalGroup(
            exMembersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1770, Short.MAX_VALUE)
        );
        exMembersPanelLayout.setVerticalGroup(
            exMembersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ex Members", exMembersPanel);

        newMembersPanel.setBackground(new java.awt.Color(176, 224, 230));

        javax.swing.GroupLayout newMembersPanelLayout = new javax.swing.GroupLayout(newMembersPanel);
        newMembersPanel.setLayout(newMembersPanelLayout);
        newMembersPanelLayout.setHorizontalGroup(
            newMembersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1770, Short.MAX_VALUE)
        );
        newMembersPanelLayout.setVerticalGroup(
            newMembersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("New Members", newMembersPanel);

        javax.swing.GroupLayout membershipPanelLayout = new javax.swing.GroupLayout(membershipPanel);
        membershipPanel.setLayout(membershipPanelLayout);
        membershipPanelLayout.setHorizontalGroup(
            membershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        membershipPanelLayout.setVerticalGroup(
            membershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        mainTabbedPane.addTab("Membership", membershipPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );

        mainTabbedPane.getAccessibleContext().setAccessibleName("Membership");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainscreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addVidPanel;
    private javax.swing.JPanel borrowPanel;
    private javax.swing.JPanel deleteVidPanel;
    private javax.swing.JPanel exMembersPanel;
    private javax.swing.JPanel issuancePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel lentVidsPanel;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel membersPanel;
    private javax.swing.JPanel membershipPanel;
    private javax.swing.JPanel myProfilePanel;
    private javax.swing.JPanel newMembersPanel;
    private javax.swing.JPanel owenedVidsPanel;
    private javax.swing.JPanel returnPanel;
    private javax.swing.JPanel revenuePanel;
    private javax.swing.JTabbedPane revenueTabbedPane;
    private javax.swing.JTabbedPane vidIssuanceTabbedPane;
    private javax.swing.JPanel vidRecordsPanel;
    private javax.swing.JTabbedPane vidRecordsTabbedPane;
    // End of variables declaration//GEN-END:variables
}
